export const locationColumnNames= [
  { displayName: 'Location Description *', key: 'loc_desc' },
  { displayName: 'Location Type *', key: 'loc_type' },
  { displayName: 'GLN Code', key: 'gln_code' },
  { displayName: 'IATA Code', key: 'iata_code' },
  { displayName: 'Longitude *', key: 'longitude' },
  { displayName: 'Latitude *', key: 'latitude' },
  { displayName: 'Time Zone *', key: 'time_zone' },
  { displayName: 'City *', key: 'city' },
  { displayName: 'State *', key: 'state' },
  { displayName: 'Country *', key: 'country' },
  { displayName: 'Pincode *', key: 'pincode' },
];

export const vehicleColumnNames = [
  { displayName: 'Location ID', key: 'location_id' },
  { displayName: 'Unlimited Usage', key: 'unlimited_usage' },
  { displayName: 'Individual Resource', key: 'individual_resource' },
  { displayName: 'Validity From', key: 'validity_from' },
  { displayName: 'Validity To', key: 'validity_to' },
  { displayName: 'Vehicle Type', key: 'vehicle_type' },
  { displayName: 'Vehicle Group', key: 'vehicle_group' },
  { displayName: 'Ownership', key: 'ownership' },
  { displayName: 'Payload Weight', key: 'payload_weight' },
  { displayName: 'Cubic Capacity', key: 'cubic_capacity' },
  { displayName: 'Interior Length', key: 'interior_length' },
  { displayName: 'Interior Width', key: 'interior_width' },
  { displayName: 'Interior Height', key: 'interior_height' },
  { displayName: 'Tare Weight', key: 'tare_weight' },
  { displayName: 'Max Gross Weight', key: 'max_gross_weight' },
  { displayName: 'Tare Volume', key: 'tare_volume' },
  { displayName: 'Max Length', key: 'max_length' },
  { displayName: 'Max Width', key: 'max_width' },
  { displayName: 'Max Height', key: 'max_height' },
  { displayName: 'Downtime Starts From', key: 'downtime_starts_from' },
  { displayName: 'Downtime Ends From', key: 'downtime_ends_from' },
  { displayName: 'Downtime Location', key: 'downtime_location' },
  { displayName: 'Downtime Description', key: 'downtime_desc' },
  { displayName: 'Reason', key: 'reason' },
  { displayName: 'Vehicle Group Description', key: 'vehicle_group_desc' },
  { displayName: 'Cost Per Ton', key: 'cost_per_ton' },
];
