export type VehicleStatus = "Moving" | "Idle" | "Stopped";

// export interface Vehicle {
//   id: number;
//   vehicleNumber: string;
//   driverName: string;
//   driverPhone: string;
//   status: VehicleStatus;
//   speed: number;
//   latitude: number;
//   longitude: number;
//   location: string;
//   idleTime: number;
//   lastIdleDuration: number;
//   todayDistance: number;
//   fuelLevel: number;
//   engineOn: boolean;
//   lastUpdated: string;
//   lastStartedAt: string;
//   lastStoppedAt: string;
// }


export interface Vehicle {
  id: number;
  vehicleNumber: string;
  driverName: string;
  driverPhone: string;
  status: "Moving" | "Idle" | "Stopped";
  engineOn: boolean;
  speed: number;
  fuelLevel: number;
  idleTime: number;
  todayDistance: number;
  location: string;
  latitude: number;
  longitude: number;
  vehicleType: string;
  lastUpdated: string;
  ignitionStatus: string;
  powerStatus: string;
  gsmLevel: string;
  expiryDate: string;
  overSpeedLimit: number;
}

export interface SensorBasedVehicleMode {
  sensor: string;
  vehicleMode: string;
}


export interface VehicleTrackingApiResponse {
  rowId: number;
  latitude: string;
  longitude: string;
  speed: number;
  date: number;
  alert: string;
  direction: string;
  position: string;
  distanceCovered: number;
  odoDistance: number;
  odoMeterDevice: number;
  tankSize: number;
  deviceVolt: number;
  status: string;
  altitude: number | null;
  color: string;
  lastSeen: string;
  ignitionStatus: string;
  insideGeoFence: string;
  isOverSpeed: string;
  address: string;
  parkedTime: number;
  movingTime: number;
  idleTime: number;
  noDataTime: number;
  alertDateTime: string;
  latLngOld: string | null;
  loadTruck: string;
  loadTrailer: string;
  totalTruck: string;
  totalTrailer: string;
  vehicleBusy: string;
  fuelLitre: number;
  temperature: number;
  powerStatus: string;
  deviceStatus: string;
  gsmLevel: string;
  startParkedTime: number;
  endParkedTime: number;
  maxSpeed: number;
  averageSpeed: number;
  lastComunicationTime: number;
  isOutOfOrder: string;
  tripName: string;
  forwardOrBackward: string;
  enableLog: string;
  dateSec: number;
  digitalInput3: string;
  fuelSensorVolt: string;
  nTankSize: string;
  noOfTank: number;
  sensorCount: number;
  gpsSimICCID: string;
  madeIn: string | null;
  manufacturingDate: string | null;
  chassisNumber: string | null;
  gpsSimNo: string;
  onboardDate: string;
  speedInfo: string | null;
  defaultMileage: string;
  noDataStatus: number;
  lat: number;
  lng: number;
  topSpeed: number;
  fuelSensorType: string;
  idleEndDate: number;
  todayWorkingHours: number;
  sensorBasedVehicleMode: SensorBasedVehicleMode[];
  dashlinks: string | null;
  fuelLitres: string;
  vehicleMake: string | null;
  oprName: string;
  regNo: string;
  vehicleType: string;
  vehicleId: string;
  mobileNo: string | null;
  customMarker: string;
  deviceModel: string;
  shortName: string;
  orgId: string;
  overSpeedLimit: number;
  driverName: string;
  error: string | null;
  live: string;
  fuel: string;
  deviceId: string;
  expired: string;
  expiryDate: string;
  expiryDays: number;
  routeName: string;
  groupName: string;
  safetyParking: string;
  description: string;
  driverMobile: string;
  vehicleName: string | null;
  trackName: string;
  report: string;
  licenceExpiry: string;
  supportDetails: string;
  serial1: string;
  expiryStatus: string;
  vehicleMode: string;
  vehicleModel: string;
  licenceType: string;
  licenceExpiryStatus: string | null;
  rigMode: string;
  secondaryEngineHours: number;
  vehicleList: unknown[] | null;
  userId: string | null;
  macid: string | null;
  appid: string | null;
  group: string | null;
  language: string | null;
  immobilizer: string;
  timeZone: string;
  calibrateMode: string;
  engineStatus: string;
  communicatingPortNo: string;
  isAsset: boolean;
  vehicleTypeLabel: string;
  expectedFuelMileage: number;
  immobilizerStatus: string | null;
  fcode: string;
  cameraEnabled: boolean;
  ac: boolean;
}