// "use client";
// import type { Metadata } from "next";
// // import localFont from "next/font/local";
// import "./globals.css";
// import ReduxProvider from "@/store/redux-provider";
// import Header from "@/Components/Header";
// import Footer from "@/Components/Footer";
// import { ThemeProvider, Grid } from '@mui/material';
// import CssBaseline from "@mui/material/CssBaseline";
// import theme from "@/theme";
// import { SessionProvider } from "next-auth/react";
// // const geistSans = localFont({
// //   src: "./fonts/GeistVF.woff",
// //   variable: "--font-geist-sans",
// //   weight: "100 900",
// // });
// // const geistMono = localFont({
// //   src: "./fonts/GeistMonoVF.woff",
// //   variable: "--font-geist-mono",
// //   weight: "100 900",
// // });

// export const metadata: Metadata = {
//   title: "Truk app",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body>
//         <SessionProvider>
//           <ThemeProvider theme={theme}>
//             <CssBaseline />
//             <ReduxProvider>
//               <Header />
//               <Grid sx={{ marginTop: { xs: '20px', md: '33px' }, padding: '15px', backgroundColor: "#FAF1F8", minHeight: '70vh' }}>
//                 {children}
//               </Grid>
//               <Footer />
//             </ReduxProvider>
//           </ThemeProvider>
//         </SessionProvider>
//       </body>
//     </html>
//   );
// }


import type { Metadata } from "next";
import LayoutClientWrapper from "./LayoutClientWrapper";

export const metadata: Metadata = {
  title: "Truk App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <LayoutClientWrapper>{children}</LayoutClientWrapper>
      </body>
    </html>
  );
}
